name: Caller workflow

on:
 workflow_dispatch:
 
 
jobs:

    trigger_javaci: 
      
       uses: shanmugamrak/reusable-workflow-ci/.github/workflows/javaci.yml@main
      
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
